### ISSUE TITLE
Set up milestones, create a current release

### ISSUE THREAD

**Issue by oubiwann** [lfex/lmud#3]
Tasks:
* [x] Create milestone 0.4.0 (add tickets)
* [x] Create milestone 0.5.0 (add tickets)
* [x] Create milestone 0.6.0 (add tickets)
* [ ] Create a release for current state before making code changes (0.4.0)

**Comment by oubiwann** [comment]
Can't really do a full release of 0.4.0 with no code changes, since it's so old. It was running LFE 0.8 and Erlang 17. I'm just going to tag the last commit from 2014 as 0.4.0.

I'll get it running again with a recent Erlang + LFE, and put that in 0.5.0.
