### ISSUE TITLE
Support running multiple games / worlds simultaneously

### ISSUE THREAD

**Issue by oubiwann** [lfex/lmud#48]
Tasks:
* [ ] Refactor game server to spawn children dynamically, for each game the server runs
* [ ] Support characters moving between games
* [ ] Support "incarnating" as a different character in another game (e.g., dream state being a different character in a different game)
