### ISSUE TITLE
Add basic NPC support

### ISSUE THREAD

**Issue by oubiwann** [lfex/lmud#51]
Features:
* [ ] NPC data
  * [ ] data modelling
  * [ ] characteristics such as friendly, tame, wild/fearful, hostile
* [ ] Support animals
* [ ] Support sentients (classic NPCs)
* [ ] Support monsters
* [ ] All animals, sentients, and monsters will use the same underlying NPC code
