### ISSUE TITLE
Add time to lmud

### ISSUE THREAD

**Issue by oubiwann** [lfex/lmud#52]
Features:
* [ ] Add time tracking
* [ ] Support times of day
* [ ] Support times of night
* [ ] Days of week
* [ ] Months
* [ ] Support seasons
* [ ] Support years
* [ ] Room descriptions need to be augmented to show time / season changes since last description
* [ ] Player characters need to track the last time update received (only show in description if they've not seen the time change)
* [ ] Add new "time" command
