### ISSUE TITLE
Create a REST API

### ISSUE THREAD

**Issue by oubiwann** [lfex/lmud#73]
Features:
* [ ] Add an SSL/TLS support
* [ ] Add an HTTP server
* [ ] Support JSON response data
* [ ] Secure requests (e.g., support HMAC / Bearer tokens / etc.)
* [ ] Create an initial set of routes
* [ ] Standardize on Twine format
